SPRING_APPLICATION_NAME=StudentGrader

# Database (Render MySQL or external DB)
SPRING_DATASOURCE_URL=jdbc:mysql://<HOST>:<PORT>/<DB_NAME>
SPRING_DATASOURCE_USERNAME=<USERNAME>
SPRING_DATASOURCE_PASSWORD=<PASSWORD>

# JPA / Hibernate
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
SPRING_SQL_INIT_MODE=always

# ===============================

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# MAIL CONFIGURATION (GMAIL)
# ===============================


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhiseamarwagholi@gmail.com
spring.mail.password=wtle zgig ykyw fogr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

